# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'PaintWithRx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit',              '~> 3.2.0'
  pod 'MBProgressHUD',        '~> 1.0'
  pod 'RxSwift',              '~> 3.2.0'
  pod 'RxCocoa',              '~> 3.2.0'
  pod 'RxDataSources',        '~> 1.0.3'
  # Pods for PaintWithRx

  target 'PaintWithRxTests' do
    inherit! :search_paths

end

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

  target 'PaintWithRxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
